#fact_checker_agent/models/search_helper_models.py

from pydantic import BaseModel, Field
from typing import Optional

class Payload(BaseModel):
    link: str = Field(..., description="URL of the search result.")
    title: str = Field(..., description="Title of the search result.")
    position: Optional[int] = Field(None, description="Position of the search result in the list.")
    source: Optional[str] = Field(None, description="Source of the search result.")
    date: Optional[str] = Field(None, description="Date of the search result.")
    snippet: Optional[str] = Field(None, description="Snippet of the search result.")
    duration: Optional[str] = Field(None, description="Duration of the video.")
    content_summary: Optional[str] = Field(None, description="Summary of the content, generated by the model.")